### ISSUE TITLE
Is there a way to convert C++ headerfiles into Odin?

### ISSUE THREAD

**Issue by Joe23232** [Breush/odin-binding-generator#12]
Is there a way to convert C++ headerfiles into Odin?

**Comment by Breush** [comment]
Hi @Joe23232 ,

According to https://github.com/odin-lang/Odin/wiki/Binding-to-C
it is not made easy to bind with C++ directly.

People usually write a small C wrapper that allow accessing the
C++ API with C-like functions.

Does that make sense?

**Comment by Joe23232** [comment]
> Hi @Joe23232 ,
> 
> According to https://github.com/odin-lang/Odin/wiki/Binding-to-C
> it is not made easy to bind with C++ directly.
> 
> People usually write a small C wrapper that allow accessing the
> C++ API with C-like functions.
> 
> Does that make sense?

Hey man,

Yes it does make sense, but is it then somehow possible to write a small C wrapper to access the C++ API and then convert the C wrapper file into Odin, that way Odin would be accessing the C++ API?

I am kinda new to programming so I don't quite know how this kind of stuff works.

**Comment by Breush** [comment]
To answer simply: yes, it is possible.
Once you have your C API (hiding the C++ details) you can either write the Odin binding by hand or use [odin-binding-generator](https://github.com/Breush/odin-binding-generator) to automate this process.

But I am not aware of any tool that can automate the creation of your C API from the C++.
As far as I know, it has to be done by hand.
Which, depending on the scope of the C++ project, it can be pretty time-consuming.

However:
- Big C++ projects (for instance [Bullet physics engine](https://github.com/bulletphysics/bullet3)) should already have some official or non-official C API project ([here's one I found](https://github.com/chriscamacho/bulletCapi)). Because the problem of interfacing with C++ programs occurs in many other programming languages - it's way easier to interface with C.
- Small or your own C++ projects can easily be C-ify if you don't need to expose too many functionalities. Some [help from StackOverflow](https://stackoverflow.com/questions/51699877/how-to-create-c-api-to-c-function) if you need.

Hope it helps you. :)

**Comment by Joe23232** [comment]
Thanks man it does help :)
