### ISSUE TITLE
Halp with cuting off xcb enum value prefix

### ISSUE THREAD

**Issue by valignatev** [Breush/odin-binding-generator#18]
Hey! xcb enums generally have `_t` postfix that isn't included in the enum _value_, like this:

```odin
window_class_t :: enum i32 {
    WINDOW_CLASS_COPY_FROM_PARENT = 0,
    WINDOW_CLASS_INPUT_OUTPUT = 1,
    WINDOW_CLASS_INPUT_ONLY = 2,
};
```
I'd like to remove `WINDOW_CLASS` from enum value, but I want to leave `_t` in enum name, so the result would be this:
```odin
window_class_t :: enum i32 {
    COPY_FROM_PARENT = 0,
    INPUT_OUTPUT = 1,
    INPUT_ONLY = 2,
};
```
I feel like it should be possible with some combination of option flags, but I can't quite get it right. Is this actually possible?

I would be ok to remove `_t` entirely, but unfortunately it creates name conflicts between some pseudo-types and function names

**Comment by Breush** [comment]
Thanks for reporting, should be fixed with b6895ef90780793098166da2bdb771491e621ce6

**Comment by valignatev** [comment]
This isn't really an issue, I just wonder if this is possible to achieve :) The issue I posted in #17 is fixed indeed

**Comment by Breush** [comment]
Yeap, to be clear :
- There was a bug that made your request not easy to do before fixing #17.
- The code you provided in #17 should do what you describe here.

Fact is:
```odin
    options.enumValueNameRemove = true;
    options.enumValueNameRemovePostfixes = []string{"_t"};
 ```
 does exactly that.
 
 It means "hey, remove that enum name "window_class_t" from its enum values like "WINDOW_CLASS_COPY_FROM_PARENT" but when you do that, forget about that "_t" postfix in the enum name so that you can remove it without issues.

**Comment by valignatev** [comment]
Ohhh, I see. Yeah it totally works now, thanks again!
