### ISSUE TITLE
Failed to parse extern function without argument name

### ISSUE THREAD

**Issue by valignatev** [Breush/odin-binding-generator#20]
Hey! I'm trying to bind against xlib, and when I'm done cutting out all the macros and other irrelevant stuff, I get stuck on 
```
[bindgen] Error:  Expected identifier but found *.
[bindgen] ... from  parse_type
[bindgen] ... at line  1376  within this context:
>      _Xconst char*	/* name */
```

Which comes from extern declarations like
```c
extern XFontStruct *XLoadQueryFont(
    Display*		/* display */,
    _Xconst char*	/* name */
);
```
Seems like the bindings generator can't process function definition if only the type is defined? Am I doing something wrong?

**Comment by Breush** [comment]
Hey!

```c
extern XFontStruct *XLoadQueryFont(
    Display*		/* display */,
    const char*	/* name */
);
```

is parsed fine. I guess it's because of the `_Xconst` you have there. As we don't understand macros, the `_Xconst` is believed to be a identifier.

I suggest you to run the preprocessor of gcc to resolve those beforehand.

`cat xlib.h | grep -v "#include " | gcc -E - -o - | grep -v "# " > xlib-preprocessed.h`

**Comment by valignatev** [comment]
Oh you're right, I've been cutting down macros by hand to understand headers better, but for some reason this one went completely over my head. Thanks!
